//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace store_management_system_final
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_items
    {
        public Nullable<int> order_id { get; set; }
        public int item_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> list_price { get; set; }
        public Nullable<int> discount { get; set; }
    
        public virtual orders orders { get; set; }
        public virtual products products { get; set; }
    }
}
